### ISSUE TITLE
`gulp watch` error

### ISSUE THREAD

**Issue by darkwing** [mozilla/platatus#227]
Getting a weird error when running `gulp watch`:

```
$ gulp watch
[13:44:28] Requiring external module babel-core/register
Building for development
[13:44:34] Using gulpfile ~/Projects/platatus/gulpfile.babel.js
[13:44:34] Starting 'build:root'...
[13:44:34] Starting 'build:tabzilla'...
[13:44:34] Starting 'build:status'...
[13:44:34] 'build:status' errored after 9.96 ms
[13:44:34] TypeError: undefined is not a function
    at FixtureParser.readFile (/Users/dwalsh/Projects/platatus/engine/fixtureParser.js:39:19)
    at Array.map (native)
    at FixtureParser.read (/Users/dwalsh/Projects/platatus/engine/fixtureParser.js:47:80)
    at Object.buildStatus (/Users/dwalsh/Projects/platatus/engine/index.js:531:37)
    at Gulp.<anonymous> (/Users/dwalsh/Projects/platatus/gulpfile.babel.js:125:26)
    at module.exports (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
[13:44:34] Finished 'build:tabzilla' after 34 ms
[13:44:34] Finished 'build:root' after 59 ms
```

**Comment by marco-c** [comment]
Do you have up to date dependencies?

(Try `rm -rf node_modules && npm install`)

**Comment by darkwing** [comment]
```
$ rm -rf node_modules/
$ npm install

> buffertools@2.1.3 install /Users/dwalsh/Projects/platatus/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node

> unicode@0.6.1 postinstall /Users/dwalsh/Projects/platatus/node_modules/slug/node_modules/unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
fetching …
saving data as Cc.js …
saving data as Zs.js …
saving data as Po.js …
saving data as Sc.js …
saving data as Ps.js …
saving data as Pe.js …
saving data as Sm.js …
saving data as Pd.js …
saving data as Nd.js …
saving data as Lu.js …
saving data as Sk.js …
saving data as Pc.js …
saving data as Ll.js …
saving data as So.js …
saving data as Lo.js …
saving data as Pi.js …
saving data as Cf.js …
saving data as No.js …
saving data as Pf.js …
saving data as Lt.js …
saving data as Lm.js …
saving data as Mn.js …
saving data as Me.js …
saving data as Mc.js …
saving data as Nl.js …
saving data as Zl.js …
saving data as Zp.js …
saving data as Cs.js …
saving data as Co.js …
done.
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN engine img-stats@0.4.2: wanted: {"node":"~0.10"} (current: {"node":"0.12.7","npm":"2.11.3"})

> ursa@0.9.1 install /Users/dwalsh/Projects/platatus/node_modules/oghliner/node_modules/travis-encrypt/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  CXX(target) Release/obj.target/ursaNative/src/asprintf.o
  SOLINK_MODULE(target) Release/ursaNative.node

> bufferutil@1.2.1 install /Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/
> utf-8-validate@1.2.1 install /Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
\
> intern@3.0.6 install /Users/dwalsh/Projects/platatus/node_modules/intern
> node support/fixdeps.js

-
> caniuse-api@1.4.1 postinstall /Users/dwalsh/Projects/platatus/node_modules/postcss-cssnext/node_modules/caniuse-api
> node generator.js

caniuse-api: Generation ok

> caniuse-api@1.4.1 postinstall /Users/dwalsh/Projects/platatus/node_modules/cssnext/node_modules/caniuse-api
> node generator.js

caniuse-api: Generation ok
/
> fsevents@1.0.6 install /Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/dwalsh/Projects/platatus/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote

> fsevents@1.0.6 install /Users/dwalsh/Projects/platatus/node_modules/cssnext/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/dwalsh/Projects/platatus/node_modules/cssnext/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote

> Platatus@0.1.0 postinstall /Users/dwalsh/Projects/platatus
> if $BUILD_POSTINSTALL; then ./node_modules/.bin/gulp build; fi

[14:45:45] Requiring external module babel-core/register
Building for development
[14:45:53] Using gulpfile ~/Projects/platatus/gulpfile.babel.js
[14:45:53] Starting 'build:root'...
[14:45:53] Starting 'build:tabzilla'...
[14:45:53] Starting 'build:status'...
[14:45:53] 'build:status' errored after 13 ms
[14:45:53] TypeError: undefined is not a function
    at FixtureParser.readFile (/Users/dwalsh/Projects/platatus/engine/fixtureParser.js:39:19)
    at Array.map (native)
    at FixtureParser.read (/Users/dwalsh/Projects/platatus/engine/fixtureParser.js:47:80)
    at Object.buildStatus (/Users/dwalsh/Projects/platatus/engine/index.js:531:37)
    at Gulp.<anonymous> (/Users/dwalsh/Projects/platatus/gulpfile.babel.js:125:26)
    at module.exports (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/dwalsh/Projects/platatus/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/dwalsh/Projects/platatus/node_modules/gulp/bin/gulp.js:129:20
[14:45:53] Finished 'build:tabzilla' after 49 ms
[14:45:53] Finished 'build:root' after 76 ms

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! Platatus@0.1.0 postinstall: `if $BUILD_POSTINSTALL; then ./node_modules/.bin/gulp build; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Platatus@0.1.0 postinstall script 'if $BUILD_POSTINSTALL; then ./node_modules/.bin/gulp build; fi'.
npm ERR! This is most likely a problem with the Platatus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if $BUILD_POSTINSTALL; then ./node_modules/.bin/gulp build; fi
npm ERR! You can get their info via:
npm ERR!     npm owner ls Platatus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by TimAbraldes** [comment]
> (Try `rm -rf node_modules && npm install`)

I think `npm update` also updates npm modules but doesn't cause re-installation of the ones that are already up to date

**Comment by marco-c** [comment]
I've often had problems with `npm update`, so I usually do `rm -rf node_modules && npm install` to avoid them.

**Comment by darkwing** [comment]
This turned out to be a node version issue; upgrading to 5.x allowed everything run properly, so closing this.
