### ISSUE TITLE
Selenium Error: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by darkwing** [mozilla/platatus#64]
When I don't run selenium manually, tests fail:

```
Suite firefox on any platform FAILED
Error: [POST http://localhost:4444/wd/hub/session] connect ECONNREFUSED
  at Server.createSession  <node_modules/intern/node_modules/leadfoot/Server.js:310:15>
  at <node_modules/intern/lib/executors/Runner.js:190:22>
  at retry  <node_modules/intern/lib/util.js:723:13>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at process._tickCallback  <node.js:355:11>

TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
```

selenium.log shows the following error:

```
Error: Invalid or corrupt jarfile tests/support/var/selenium-server-standalone-2.48.2.jar
```

**Comment by darkwing** [comment]
Upon further inspection, if I delete the .jar file I had (which was somehow 0k) and re-run tests, everything works.  Closing this as some fluke that my jar didn't download properly.
